version: '3.5'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-passwd}
      POSTGRES_DB: ${DB_DATABASE:-database}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - database

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD:-passwd}
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - database
    depends_on:
      - postgres


  redis:
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"

networks:
  database:
    driver: bridge

volumes:
  postgres:
  pgadmin:
