version: '3.5'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-passwd}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres

  redis:
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${DB_DEFAULT_PASSWORD:-passwd}
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
